- name: create ec2 and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-00329eaa2a9c24c6f
    ami_id: ami-0220d79f3f480ecf5
   # domain_name: daws88s.online
    env: dev
   # action: create
    instances:
      - mongodb
      - catalogue
  tasks:
    ### CREATE ###
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: Print the ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"